 
---
title: "MethyLImp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{missMethy}
  %\VignetteEngine{knitr::latex}
  \usepackage[utf8]{inputenc}
---

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\title{The \Rpackage{methyLImp} Package}
\author{Pietro Di Lena}
\begin{document}
maketitle
\section{ About the package }
The \Rpackage{methyLImp} implements a missing data imputation method based on single imputation linear regression,
especially designed for and tested on DNA methylation data [1].

\section{Installation}

The package doesn't have any dependencies from other Bioconductor packages.

Installing the latest package from a local copy (assuming it is in the current working
directory of your R session):

<<UnevaluatedCode, eval=FALSE>>=
install.packages('methyLImp_0.9.9.tar.gz', repos=NULL, type='source')
@

\section{Trying it out}
The package contains a subset of a real 450K Illumina array data, \Robject{GSE64495}, which contains beta values of 100 samples for 200 CpGs with no missing values and it can be used to explore the function quickly:

<<code-block, keep.source=TRUE>>=
library('methyLImp')
# load in methyLImp dataset
data(gse64495)
# display dimensions of data matrix
dim(gse64495)
@

\section{Suggested analysis workflow}

\subsection{Load data}

The methylation data array of either beta or M values has to be split into a CpG labels vector and the corresponding methylation array.

\subsection{Example workflow}
<<workflow, keep.source=TRUE>>=

data(gse64495)
# load in methyLImp dataset containing no missing value

rownames(gse64495) <- as.vector(as.character(gse64495[,1]))
gse64495          <- t(gse64495[,-1])

gen_rand_NA(dat, frac) {

	m_CpG <- nrow(dat)
	n_samples <- ncol(dat)
	NA_tot <- round(frac * m_CpG * n_samples, 1)

	set.seed(1)
        rand_CpG <- sample.int(m_CpG,NA_tot,replace=TRUE)
	rand_sample <- sample.int(n_samples,NA_tot,replace=TRUE)
	for(i in 1:NA_tot) {
	    dat[rand_CpG[i], rand_sample[i]] <- NA
	}
}

NA_frac <- 0.1
gse64495_miss <- gen_rand_NA(gse64495, NA_frac)
#generate the desired fraction (<=1) of missing values at random in the dataset

gse64495_imputed = methyLImp(gse64495_miss, min=0, max=1)
# impute missing data with methyLImp method

# compare statistics of imputed and original values


@

\section{References}

[1] Di Lena P, Sala C, Prodi A, Nardini C. Missing value estimation methods for DNA methylation data. submitted to Bioinformatics

\end{document}


